name: check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup npm
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: |
         cd HugeTodoList && npm install
    - name: Analysing the code with svelte check
      run: |
         cd HugeTodoList && npm run check
    - name: lint the code
      run: |
         cd HugeTodoList && npm run format && npm run lint
