name: check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup npm
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: |
         cd HugeTodoList && npm install 
    - name: create .env file
      run : |
         cd HugeTodoList
         touch .env
         echo DATABASE_URL="file:./dev.db" >> .env
    - name: prepare primsa database
      run: |
         cd HugeTodoList && npm i @prisma/client && npx prisma db push && npx prisma generate
    - name: Analysing the code with svelte check
      run: |
         cd HugeTodoList && npm run check
    - name: lint the code
      run: |
         cd HugeTodoList && npm run format && npm run lint
